version: 2

defaults: &defaults
  working_directory: ~/project/bootstrap-admin-layout
  docker:
    - image: banian/node

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: ~/project
          paths:
            - bootstrap-admin-layout

  docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish Docs
          command: yarn docs-publish

workflows:
  version: 2
  setup-and-build:
    jobs:
      - setup

      - docs:
          requires:
            - setup
          filters:
            branches:
              only:
                - master
